version: "3.8"

x-hz-common-settings: &hz-common-settings
  image: hazelcast/hazelcast:latest
  networks:
    - hazelcast-network

x-common-env: &hz-common-env
  HZ_CLUSTERNAME: dev

services:
  cassandra-node-1:
    image: cassandra:latest
    container_name: cassandra-node-1
    environment:
      - CASSANDRA_CLUSTER_NAME=FeedbackCluster
    ports:
      - "9042:9042"
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE keyspaces;'"]
      interval: 5s
      timeout: 3s
      retries: 25

  cassandra-node-2:
    image: cassandra:latest
    container_name: cassandra-node-2
    depends_on:
      cassandra-node-1:
        condition: service_healthy
    environment:
      - CASSANDRA_SEEDS=cassandra-node-1
      - CASSANDRA_CLUSTER_NAME=FeedbackCluster
    networks:
      - cassandra-network

  feedback-ddl:
    image: feedback-ddl
    build:
      context: .
      dockerfile: feedback_service/data_access/tables_creation/Dockerfile
    volumes:
      - ./feedback_service/data_access/tables_creation:/code
    environment:
      PORT: "9042"
      CASSANDRA_SEEDS: "cassandra-node-1"
    networks:
      - cassandra-network
    depends_on:
      cassandra-node-1:
        condition: service_healthy

  feedback-service:
    image: feedback-service
    build:
      context: .
      dockerfile: feedback_service/Dockerfile
    environment:
      PORT: "8080"
      CASSANDRA_PORT: "9042"
      CASSANDRA_SEEDS: "cassandra-node-1"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    networks:
      - cassandra-network
      - services-network
    depends_on:
      feedback-ddl:
        condition: service_completed_successfully

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - services-network


  hazel-node-1:
    <<: *hz-common-settings
    container_name: hazel-node-1
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-1:5701"
    ports:
      - "5701:5701"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5701/hazelcast/health/node-state",
        ]
      interval: 3s
      timeout: 1s
      retries: 15
      start_period: 5s

  hazel-node-2:
    <<: *hz-common-settings
    container_name: hazel-node-2
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-2:5701"
    ports:
      - "5702:5701"
    depends_on:
      hazel-node-1:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5701/hazelcast/health/node-state",
        ]
      interval: 3s
      timeout: 1s
      retries: 15
      start_period: 5s


  course-service:
    container_name: course-service
    build:
      context: .
      dockerfile: CourseService/Dockerfile
    image: course-service
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      PYTHONPATH: /app
      HAZELCAST_CLUSTER_NAME: "dev"
      HAZELCAST_ADDRESSES: "hazel-node-1:5701,hazel-node-2:5701"
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      mongodb:
        condition: service_started
      hazel-node-1:
        condition: service_healthy
      hazel-node-2:
        condition: service_healthy
    networks:
      - services-network
      - hazelcast-network

  entry-endpoint:
    container_name: entry-endpoint
    build:
      context: .
      dockerfile: EntryEndpoint/Dockerfile
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - course-service
    networks:
      - services-network

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: mock
      POSTGRES_DB: postgres
    volumes:
      - ./user_service/data_access/postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - postgres-network

  postgres-init:
    image: postgres:latest
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      PGPASSWORD: "mock"
    volumes:
      - ./user_service/data_access/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [
        "psql",
        "-h",
        "postgres-db",
        "-U",
        "postgres",
        "-d",
        "postgres",
        "-a",
        "-f",
        "/docker-entrypoint-initdb.d/init.sql",
      ]
    networks:
      - postgres-network

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    depends_on:
      postgres-init:
        condition: service_completed_successfully
    volumes:
      - .:/code
    environment:
      DB_HOST: postgres-db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: mock

      PORT: 8180
    ports:
      - "8180:8180"
    networks:
      - postgres-network
      - services-network


networks:
  services-network:
    driver: bridge
    name: services-network
  hazelcast-network:
    driver: bridge
    name: hazelcast-network
  cassandra-network:
    driver: bridge
    name: cassandra-network
  postgres-network:
    driver: bridge
    name: postgres-network
